### ISSUE TITLE
Questions for Session

### ISSUE THREAD

**Issue by xx00a** [xx00a/Group6#55]
- How granular should the use cases be? For example, do we need to capture the various variations (e.g. sort by low to high) or just focus on the interaction with actor to the system?
- We see (5) five reports; but within all five there are 32 variations?
- What's the user interface supposed to look like?

**Comment by 40522829** [comment]
How granular should the use cases be? For example, do we need to capture the various variations (e.g. sort by low to high) or just focus on the interaction with actor to the system?
More with the actor and the system. Professor just wants 1 user case as there is just one user role.
As statied in lab 3b: "As an HR advisor I want to produce a report on the salary of all employees so that I can support financial reporting of the organisation"

We see (5) five reports; but within all five there are 32 variations?
We guessed right where we can group the reports into countries, cities, capital, population, etc

What's the user interface supposed to look like?
For the moment, the system is there just to produce the reports.

Additional info :
- he used Java last year to pull the data from the db
- GitHub Actions will be used later in the module for releases (not available yet)
- to create UseCases, install the "Diagrams.net Integration" in IntelliJ (draw.io)
- use Database Navigator plugin in IntelliJ to connect to the db
